spring.application.name=deal
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_bank
spring.datasource.username=postgres
spring.datasource.password=!EqeMn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port=8082
calculator.offers.url=http://localhost:8081/calculator/offers
calculator.calc.url=http://localhost:8081/calculator/calc