spring.application.name=calculator
loan.baseRate=10.0
loan.insurancePrice=100000
validation.email.pattern=^[a-z0-9A-Z_!#$%&'*+/=?`{|}~^.-]+@[a-z0-9A-Z.-]+$
validation.passport.series.pattern=^\\d{4}$
validation.passport.number.pattern=^\\d{6}$
validation.name.pattern=^[a-zA-Z]{2,30}$