spring.application.name=statement
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_bank
spring.datasource.username=postgres
spring.datasource.password=!EqeMn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8083
deal.offers.url=http://localhost:8082/deal/statement
deal.selectLoanOffer.url=http://localhost:8082/deal/offer/select
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
logging.level.liquibase=INFO